Repository AY2425S2-CS2113-T12-1/tp, pull requests merged in 2025-04, with the labels that each got.

#77 Developer Guide: Added overall architecture information under design and implementation. Read desc
  docs/DeveloperGuide.md
  docs/diagrams/Architecture.puml
  docs/pictures/Architecture.png
  docs/team/johndoe.md
Labels: priority.High

#74 Branch-DG-V1: Start on adding to DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/diagrams/Architecture.puml
  docs/diagrams/RegisterPatientSequenceDiagram.puml
  docs/pictures/Architecture.png
  docs/pictures/RegisterPatientSequenceDiagram.png
  docs/team/johndoe.md
Labels: priority.High

#80 Implement DG-V1 with Application Startup Load Data and Application Shutdown Save Data functionalities.
  docs/DeveloperGuide.md
  docs/diagrams/ApplicationShutdownSaveData.png
  docs/diagrams/ApplicationStartupLoadData.png
Labels: priority.High, severity.High

#89 Added JUnit tests for ui and storage components.
  hospitalData/MediNote_Doctor_Data.txt
  hospitalData/MediNote_Patient_Data.txt
  src/test/java/seedu/medinote/TestUtil.java
  src/test/java/seedu/medinote/commands/DeleteDoctorTest.java
  src/test/java/seedu/medinote/storage/EnsureFilesExistTest.java
  src/test/java/seedu/medinote/storage/LoadDataTest.java
  src/test/java/seedu/medinote/storage/SaveDataTest.java
  src/test/java/seedu/medinote/ui/UiTest.java
Labels: priority.High, severity.High

#94 Add UG portion and PPP for li-junxian
  docs/UserGuide.md
  docs/team/li-junxian.md
  src/main/java/seedu/medinote/manager/PatientListManager.java
Labels: priority.High, severity.High

#128 Rename jackson_hu.md to jhu0748.md
  docs/team/jhu0748.md
Labels: severity.Low

#191 Java CI fix
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#212 Improvements on invalid format data entries in data files.
  src/main/java/seedu/medinote/commands/DoctorLister.java
  src/main/java/seedu/medinote/commands/DoctorViewer.java
  src/main/java/seedu/medinote/commands/ViewDoctorAttributes.java
  src/main/java/seedu/medinote/manager/DoctorListManager.java
  src/main/java/seedu/medinote/manager/PatientListManager.java
  src/main/java/seedu/medinote/person/Doctor.java
  src/main/java/seedu/medinote/storage/LoadData.java
  src/main/java/seedu/medinote/storage/SaveData.java
  src/test/java/seedu/medinote/person/DoctorTest.java
  src/test/java/seedu/medinote/storage/LoadDataTest.java
  src/test/java/seedu/medinote/storage/SaveDataTest.java
Labels: priority.High, severity.High

#215 Raida-Final-Commit
  docs/team/raidanus.md
  src/main/java/seedu/medinote/commands/DoctorUpdater.java
  src/main/java/seedu/medinote/commands/PatientUpdater.java
  src/test/java/seedu/medinote/commands/DoctorUpdaterTest.java
Labels: priority.High
